name: docker-build
# refs: https://github.com/marketplace/actions/build-and-push-docker-images
on: push

jobs:
  universal-py39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # refs: https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: universal-py39/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/universal-py39:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
